# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gather-Tech.Info
email: your-email@domain.com
description: 国内、国外のTech系ニュースを分野問わず紹介
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gather-tech.info/" # the base hostname & protocol for your site
twitter_username: braitom
github_username:  braitom

paginate: 15

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-45465111-4

# Build settings
markdown: kramdown
